baseURL = 'https://plechat1.github.io/pe/'
languageCode = 'en-us'
title = 'Patchania Events'
theme = 'coming-soon'

[params]
    title = "Patchania Events Website COMING SOON!" 
    description = "Get ready to immerse yourself in vibrant energy. Stay tuned for our launch!"
    favicon = ""
    message = "" 
    release = "October 1, 2025"
    background = ""
    enableVideoSound = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'